### ISSUE TITLE
Not working on some bootstrap style links

### ISSUE THREAD

**Issue by 2braincells2go** [andrastoth/AutomaticActionsManagement#1]
Hello Mr Andras!

Great job on the extension, really cool.

At first did not think it working, had to restart Chrome to get it working. Now working on most links in visual mode but not on code like this:

`	<div class="mbr-buttons mbr-buttons--center">
		<a href="http://google.com" class="mbr-buttons__btn btn btn-wrap btn-xs-lg btn-default" target="_blank">START EDITOR</a>
	</div>`

Thought you may like to know.

Cheers,

Woody

**Comment by 2braincells2go** [comment]
Thanks!

**Comment by andrastoth** [comment]
Hi Woody,

Thank you for the comment.
Your bootstrap working for me.
I think your selected item is a div, please check it on settings page.
I updated the visual selection.
The selected item will appear in the (left,top) on the page.

I hope it will help to you.

**Comment by 2braincells2go** [comment]
Sorry Andras, I closed and thanked you by mistake:) Had two GitHub pages open on my mobile and mistakenly closed wrong one.

Yes, it was in div. Think all is well now.

Thank you for explaining.
